--- Search fallback config
--- @class SearchFallback
--- @field enable boolean Whenever enable this search fallback or not
--- @field engine string Choose a fallback search engine, recommended soundcloud and youtube